In [1]:
#importing the libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
#Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [5]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [7]:
independent=dataset[['age', 'bmi', 'children','sex_male','smoker_yes']]
dependent=dataset['charges']

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid={'criterion':['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],'max_features':[None,'sqrt','log2'],
             'splitter':['best','random']}
grid=GridSearchCV(DecisionTreeRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
regressor=grid.fit(independent,dependent)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

In [13]:
y_pred=regressor.predict(independent)

In [15]:
from sklearn.metrics import r2_score
r_score=r2_score(dependent,y_pred)
r_score

0.998667156135576

In [17]:
re=grid.cv_results_
print("The R_score value for best parameter{}:".format(grid.best_params_))

The R_score value for best parameter{'criterion': 'poisson', 'max_features': None, 'splitter': 'best'}:

In [19]:
table=pd.DataFrame.from_dict(re)

In [21]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.007635,0.000635,0.005454,0.001461,squared_error,None,best,"{'criterion': 'squared_error', 'max_features':...",0.730335,0.645430,0.725078,0.749332,0.682717,0.706578,0.037531,4
1,0.010327,0.004389,0.004790,0.001241,squared_error,None,random,"{'criterion': 'squared_error', 'max_features':...",0.665778,0.623502,0.705870,0.707541,0.731985,0.686935,0.038168,12
2,0.009312,0.004429,0.005496,0.002368,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.743087,0.628625,0.655900,0.715234,0.671308,0.682831,0.041175,15
3,0.013868,0.011911,0.006495,0.002010,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.670522,0.467038,0.486706,0.655516,0.557121,0.567381,0.083772,24
4,0.018529,0.008488,0.007096,0.001254,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.663047,0.633800,0.483338,0.683932,0.679438,0.628711,0.074781,21
5,0.013858,0.002476,0.011782,0.004307,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.666935,0.561235,0.715018,0.682879,0.707589,0.666731,0.055482,18
6,0.017535,0.006773,0.006378,0.002377,friedman_mse,None,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.718364,0.648887,0.741394,0.734461,0.675774,0.703776,0.035683,6
7,0.011189,0.003667,0.004642,0.001777,friedman_mse,None,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.700656,0.635622,0.726046,0.685719,0.777342,0.705077,0.046648,5
8,0.006949,0.001146,0.005127,0.001558,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.772674,0.517923,0.764805,0.715541,0.738724,0.701934,0.094187,7
9,0.008270,0.001715,0.004759,0.001782,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.645039,0.553958,0.618281,0.632422,0.594932,0.608926,0.032128,23
10,0.007816,0.001781,0.003493,0.002959,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.728415,0.614333,0.728863,0.651155,0.730427,0.690639,0.048688,11
11,0.010546,0.003472,0.005157,0.003851,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.702321,0.436844,0.690688,0.666941,0.701771,0.639713,0.102241,20
12,0.042741,0.006803,0.004564,0.002882,absolute_error,None,best,"{'criterion': 'absolute_error', 'max_features'...",0.736407,0.561225,0.708715,0.714056,0.738398,0.691760,0.066321,10
13,0.033677,0.002157,0.003507,0.002955,absolute_error,None,random,"{'criterion': 'absolute_error', 'max_features'...",0.671797,0.611833,0.731880,0.718123,0.753213,0.697369,0.050420,8
14,0.025450,0.002724,0.003585,0.001048,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.746524,0.583687,0.707798,0.683666,0.738939,0.692123,0.058697,9
15,0.019327,0.004564,0.005090,0.002049,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.762299,0.658813,0.679907,0.688898,0.636454,0.685274,0.042564,13
16,0.027375,0.001178,0.003608,0.001505,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.725018,0.581633,0.644926,0.693791,0.760271,0.681128,0.062546,16
17,0.020797,0.002436,0.002738,0.001649,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.700424,0.574016,0.667457,0.681383,0.645291,0.653714,0.043724,19
18,0.010799,0.001939,0.004233,0.002488,poisson,None,best,"{'criterion': 'poisson', 'max_features': None,...",0.749054,0.655072,0.770031,0.730780,0.699925,0.720973,0.040193,1
19,0.009787,0.001829,0.005024,0.003373,poisson,None,random,"{'criterion': 'poisson', 'max_features': None,...",0.727812,0.653554,0.702030,0.732478,0.721445,0.707464,0.028883,3
20,0.008846,0.002689,0.003116,0.002646,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.716194,0.557638,0.724122,0.704222,0.715878,0.683611,0.063306,14
21,0.010246,0.001290,0.002915,0.002137,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.668611,0.548165,0.666573,0.651322,0.554355,0.617805,0.054697,22
22,0.011154,0.003192,0.003212,0.001785,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.735020,0.636690,0.738235,0.712666,0.762303,0.716983,0.043119,2
23,0.008455,0.001398,0.001206,0.001511,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.709122,0.626655,0.735682,0.672194,0.629443,0.674619,0.043050,17