In [1]:
#importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [6]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [7]:
independent=dataset[['age','bmi','children','sex_male','smoker_yes']]
dependent=dataset['charges']

In [8]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid={'kernel':['rbf','poly','sigmoid','linear'],
            'c':[10,100,1000,2000,3000],'gamma':['auto','scale']}

grid=GridSearchCV(SVR(),param_grid,refit=True,verbose=3,n_jobs=-1)
#fitting the model for grid search
grid.fit(X_train,y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

ValueError: Invalid parameter 'c' for estimator SVR(). Valid parameters are: ['C', 'cache_size', 'coef0', 'degree', 'epsilon', 'gamma', 'kernel', 'max_iter', 'shrinking', 'tol', 'verbose'].

In [ ]:
# print best parameter after tuning
#print (grid.best_params_)
re=grid.cv_results_

print("The R_score value for best parameter {}:".format(grid.best_param_))


The R_score value for best parameter {"c': 3000, 'gamma': 'scale', 'kernel': 'poly'}:

In [ ]:
table=pd.DataFrame.from_dict(re)

In [ ]:
table

In [ ]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex_male 0 or 1:"))
smoker_yes_input=int(input("Smoke_yes 0 or 1:"))


Age:32
BMI:43
Children:2
Sex_male :0
Smoker_yes:1

In [ ]:
Future_prediction=grid.predict([[age_input,children_input,sex_male_input,smoker_yes_input]])#change the params
print("Future_prediction={}".format(Future_prediction))

Future_prediction